name: Run Telegram Bot (every 10 minutes)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot logic
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          TOPIC_ID: ${{ secrets.TOPIC_ID }}
        run: python bot/main.py

      - name: Commit updated message ID
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase
          git add state/message_id.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update message_id.txt"
            git push
          fi
